//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.OfertasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wsofertas.duoc.cl/", ConfigurationName="OfertasWS.OfertasWS")]
    public interface OfertasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.wsofertas.duoc.cl/OfertasWS/procesarLoginRequest", ReplyAction="http://ws.wsofertas.duoc.cl/OfertasWS/procesarLoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.OfertasWS.procesarLoginResponse procesarLogin(WindowsFormsApp1.OfertasWS.procesarLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.wsofertas.duoc.cl/OfertasWS/procesarLoginRequest", ReplyAction="http://ws.wsofertas.duoc.cl/OfertasWS/procesarLoginResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.OfertasWS.procesarLoginResponse> procesarLoginAsync(WindowsFormsApp1.OfertasWS.procesarLoginRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsofertas.duoc.cl/")]
    public partial class loginRequestVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsofertas.duoc.cl/")]
    public partial class loginResponseVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRespuestaField;
        
        private long codigoUsuarioField;
        
        private string respuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long codigoUsuario {
            get {
                return this.codigoUsuarioField;
            }
            set {
                this.codigoUsuarioField = value;
                this.RaisePropertyChanged("codigoUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarLogin", WrapperNamespace="http://ws.wsofertas.duoc.cl/", IsWrapped=true)]
    public partial class procesarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsofertas.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.OfertasWS.loginRequestVO loginRequest;
        
        public procesarLoginRequest() {
        }
        
        public procesarLoginRequest(WindowsFormsApp1.OfertasWS.loginRequestVO loginRequest) {
            this.loginRequest = loginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarLoginResponse", WrapperNamespace="http://ws.wsofertas.duoc.cl/", IsWrapped=true)]
    public partial class procesarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsofertas.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.OfertasWS.loginResponseVO @return;
        
        public procesarLoginResponse() {
        }
        
        public procesarLoginResponse(WindowsFormsApp1.OfertasWS.loginResponseVO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfertasWSChannel : WindowsFormsApp1.OfertasWS.OfertasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertasWSClient : System.ServiceModel.ClientBase<WindowsFormsApp1.OfertasWS.OfertasWS>, WindowsFormsApp1.OfertasWS.OfertasWS {
        
        public OfertasWSClient() {
        }
        
        public OfertasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.OfertasWS.procesarLoginResponse WindowsFormsApp1.OfertasWS.OfertasWS.procesarLogin(WindowsFormsApp1.OfertasWS.procesarLoginRequest request) {
            return base.Channel.procesarLogin(request);
        }
        
        public WindowsFormsApp1.OfertasWS.loginResponseVO procesarLogin(WindowsFormsApp1.OfertasWS.loginRequestVO loginRequest) {
            WindowsFormsApp1.OfertasWS.procesarLoginRequest inValue = new WindowsFormsApp1.OfertasWS.procesarLoginRequest();
            inValue.loginRequest = loginRequest;
            WindowsFormsApp1.OfertasWS.procesarLoginResponse retVal = ((WindowsFormsApp1.OfertasWS.OfertasWS)(this)).procesarLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.OfertasWS.procesarLoginResponse> WindowsFormsApp1.OfertasWS.OfertasWS.procesarLoginAsync(WindowsFormsApp1.OfertasWS.procesarLoginRequest request) {
            return base.Channel.procesarLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.OfertasWS.procesarLoginResponse> procesarLoginAsync(WindowsFormsApp1.OfertasWS.loginRequestVO loginRequest) {
            WindowsFormsApp1.OfertasWS.procesarLoginRequest inValue = new WindowsFormsApp1.OfertasWS.procesarLoginRequest();
            inValue.loginRequest = loginRequest;
            return ((WindowsFormsApp1.OfertasWS.OfertasWS)(this)).procesarLoginAsync(inValue);
        }
    }
}
